default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: manda_feed_development

test:
  <<: *default
  database: manda_feed_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
